// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5b5197b4-6440-49df-b44b-901abe7fd2a4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3VwS04wgu",
    "aws_user_pools_web_client_id": "1pf04ou5anpntnbujcpq341l4h",
    "oauth": {}
};


export default awsmobile;
